In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/diegoc85/Downloads/pokedex.csv")
df

,Image,Index,Name,Type 1,Type 2,Total,HP,Attack,Defense,SP. Atk.,SP. Def,Speed
0,images/1.png,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45
1,images/2.png,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60
2,images/3.png,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80
3,images/4.png,3,Venusaur Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80
4,images/5.png,4,Charmander,Fire,NaN,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...
1210,images/1211.png,1023,Iron Crown,Steel,Psychic,590,90,72,100,122,108,98
1211,images/1212.png,1024,Terapagos Normal Form,Normal,NaN,450,90,65,85,65,85,60
1212,images/1213.png,1024,Terapagos Terastal Form,Normal,NaN,600,95,95,110,105,110,85
1213,images/1214.png,1024,Terapagos Stellar Form,Normal,NaN,700,160,105,110,130,110,85
1214,images/1215.png,1025,Pecharunt,Poison,Ghost,600,88,88,160,88,88,88

In [ ]:
q1_total = df['Total'].quantile(0.25)
q3_total = df['Total'].quantile(0.75)
iqr_total = q3_total - q1_total
limite_inferior_total = q1_total - 1.5 * iqr_total
limite_superior_total = q3_total + 1.5 * iqr_total
total_out = df[(df['Total'] < limite_inferior_total) | (df['Total'] > limite_superior_total)]
total_outliers = total_out.shape[0]
print(f"Total de outliers encontrados: {total_outliers}")

Total de outliers encontrados: 1

In [11]:
q1_total = df['HP'].quantile(0.25)
q3_total = df['HP'].quantile(0.75)
iqr_total = q3_total - q1_total
limite_inferior_total = q1_total - 1.5 * iqr_total
limite_superior_total = q3_total + 1.5 * iqr_total
total_out = df[(df['HP'] < limite_inferior_total) | (df['HP'] > limite_superior_total)]
total_outliers = total_out.shape[0]
print(f"Total de outliers encontrados: {total_outliers}")

Total de outliers encontrados: 27

In [12]:
q1_total = df['Attack'].quantile(0.25)
q3_total = df['Attack'].quantile(0.75)
iqr_total = q3_total - q1_total
limite_inferior_total = q1_total - 1.5 * iqr_total
limite_superior_total = q3_total + 1.5 * iqr_total
total_out = df[(df['Attack'] < limite_inferior_total) | (df['Attack'] > limite_superior_total)]
total_outliers = total_out.shape[0]
print(f"Total de outliers encontrados: {total_outliers}")

Total de outliers encontrados: 13

In [13]:
q1_total = df['Defense'].quantile(0.25)
q3_total = df['Defense'].quantile(0.75)
iqr_total = q3_total - q1_total
limite_inferior_total = q1_total - 1.5 * iqr_total
limite_superior_total = q3_total + 1.5 * iqr_total
total_out = df[(df['Defense'] < limite_inferior_total) | (df['Defense'] > limite_superior_total)]
total_outliers = total_out.shape[0]
print(f"Total de outliers encontrados: {total_outliers}")

Total de outliers encontrados: 25